EndPoint/Areas/Administration/Pages/Blog/Articles/Create.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EndPoint.Areas.Administration.Pages.Blog.Articles;
[Authorize]

public class CreateModel : PageModel
{
    private readonly IArticleApplication _articleApplication;
    private readonly IArticleCategoryApplication _articleCategoryApplication;
    public SelectList ArticleCategories;
    public CreateArticle Command;

    public CreateModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
    {
        _articleApplication = articleApplication;
        _articleCategoryApplication = articleCategoryApplication;
    }

    public void OnGet()
    {
        ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
    }

    public IActionResult OnPost(CreateArticle command)
    {
        var result = _articleApplication.Create(command);
        return RedirectToPage("./Index");
    }
}

EndPoint/Areas/Administration/Pages/Blog/Articles/Edit.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EndPoint.Areas.Administration.Pages.Blog.Articles;
[Authorize]

public class EditModel : PageModel
{
    private readonly IArticleApplication _articleApplication;
    private readonly IArticleCategoryApplication _articleCategoryApplication;
    public SelectList ArticleCategories;
    public EditArticle Command;

    public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
    {
        _articleApplication = articleApplication;
        _articleCategoryApplication = articleCategoryApplication;
    }

    public void OnGet(long id)
    {
        Command = _articleApplication.GetDetails(id);
        ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
    }

    public IActionResult OnPost(EditArticle command)
    {
        var result = _articleApplication.Edit(command);
        return RedirectToPage("./Index");
    }
}

EndPoint/Areas/Administration/Pages/Shop/Films/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.Film;

namespace EndPoint.Areas.Administration.Pages.Shop.Films;

public class IndexModel : PageModel
{
    private readonly IFilmApplication _FilmApplication;
    public List<FilmViewModel> Films;

    public IndexModel(IFilmApplication FilmApplication)
    {
        _FilmApplication = FilmApplication;
    }

    [TempData] public string Message { get; set; }

    public void OnGet()
    {
        Films = _FilmApplication.GetList();
    }

    public IActionResult OnGetCreate()
    {
        var command = new CreateFilm();
        return Partial("./Create", command);
    }

    public JsonResult OnPostCreate(CreateFilm command)
    {
        var result = _FilmApplication.Create(command);
        return new JsonResult(result);
    }

    public IActionResult OnGetEdit(long id)
    {
        var Film = _FilmApplication.GetDetails(id);
        return Partial("Edit", Film);
    }

    public JsonResult OnPostEdit(EditFilm command)
    {
        var result = _FilmApplication.Edit(command);
        return new JsonResult(result);
    }

    public IActionResult OnGetRemove(long id)
    {
        var result = _FilmApplication.Remove(id);
        if (result.IsSuccedded)
            return RedirectToPage("./Index");

        Message = result.Message;
        return RedirectToPage("./Index");
    }

    public IActionResult OnGetRestore(long id)
    {
        var result = _FilmApplication.Restore(id);
        if (result.IsSuccedded)
            return RedirectToPage("./Index");

        Message = result.Message;
        return RedirectToPage("./Index");
    }
}

EndPoint/Areas/Administration/Pages/Shop/ProductCategories/Index.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductCategory;

namespace EndPoint.Areas.Administration.Pages.Shop.ProductCategories;
[Authorize]

public class IndexModel : PageModel
{
    private readonly IProductCategoryApplication _productCategoryApplication;
    public List<ProductCategoryViewModel> ProductCategories;
    public ProductCategorySearchModel SearchModel;

    public IndexModel(IProductCategoryApplication productCategoryApplication)
    {
        _productCategoryApplication = productCategoryApplication;
    }

    public void OnGet(ProductCategorySearchModel searchModel)
    {
        ProductCategories = _productCategoryApplication.Search(searchModel);
    }

    public IActionResult OnGetCreate()
    {
        return Partial("./Create", new CreateProductCategory());
    }

    public JsonResult OnPostCreate(CreateProductCategory command)
    {
        var result = _productCategoryApplication.Create(command);
        return new JsonResult(result);
    }

    public IActionResult OnGetEdit(long id)
    {
        var productCategory = _productCategoryApplication.GetDetails(id);
        return Partial("Edit", productCategory);
    }

    public JsonResult OnPostEdit(EditProductCategory command)
    {
        if (ModelState.IsValid)
        {
        }

        var result = _productCategoryApplication.Edit(command);
        return new JsonResult(result);
    }
}

EndPoint/Areas/Administration/Pages/Shop/Products/Create.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductCategory;

namespace EndPoint.Areas.Administration.Pages.Shop.Products
{
    [Authorize]

    public class CreateModel : PageModel
    {
        private readonly IProductApplication _productApplication;
        private readonly IProductCategoryApplication _productCategoryApplication;
        public CreateProduct Command;
        public SelectList ProductCategory;


        public CreateModel(IProductApplication productApplication,
    IProductCategoryApplication productCategoryApplication)
        {
            _productApplication = productApplication;
            _productCategoryApplication = productCategoryApplication;
        }
        public void OnGet()
        {
            ProductCategory = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
        }


        public IActionResult OnPost(CreateProduct command)
        {
            var result = _productApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

EndPoint/Areas/Administration/Pages/Shop/Products/Edit.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductCategory;

namespace EndPoint.Areas.Administration.Pages.Shop.Products
{
    [Authorize]

    public class EditModel : PageModel
    {
        private readonly IProductApplication _articleApplication;
        private readonly IProductCategoryApplication _articleCategoryApplication;
        public SelectList ProductCategories;
        public EditProduct Command;
        public EditModel(IProductApplication articleApplication, IProductCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }
        public void OnGet(long id)
        {
            Command = _articleApplication.GetDetails(id);
            ProductCategories = new SelectList(_articleCategoryApplication.GetProductCategories(), "Id", "Name");
        }

        public IActionResult OnPost(EditProduct command)
        {
            var result = _articleApplication.Edit(command);
            return RedirectToPage("./Index");
        }
    }
}

EndPoint/Areas/Administration/Pages/Shop/Products/Index.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductCategory;

namespace EndPoint.Areas.Administration.Pages.Shop.Products;
[Authorize]

public class IndexModel : PageModel
{
    private readonly IProductApplication _productApplication;
    private readonly IProductCategoryApplication _productCategoryApplication;
    public SelectList ProductCategories;
    public List<ProductViewModel> Products;
    public ProductSearchModel SearchModel;

    public IndexModel(IProductApplication productApplication,
        IProductCategoryApplication productCategoryApplication)
    {
        _productApplication = productApplication;
        _productCategoryApplication = productCategoryApplication;
    }

    [TempData] public string Message { get; set; }
    public void OnGet(ProductSearchModel searchModel)
    {
        ProductCategories = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
        Products = _productApplication.Search(searchModel);
    }
}

EndPoint/Areas/Administration/Pages/Shop/Slides/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.Slide;

namespace EndPoint.Areas.Administration.Pages.Shop.Slides;
[Authorize]

public class IndexModel : PageModel
{
    private readonly ISlideApplication _slideApplication;
    public List<SlideViewModel> Slides;

    public IndexModel(ISlideApplication slideApplication)
    {
        _slideApplication = slideApplication;
    }

    [TempData] public string Message { get; set; }

    public void OnGet()
    {
        Slides = _slideApplication.GetList();
    }

    public IActionResult OnGetCreate()
    {
        var command = new CreateSlide();
        return Partial("./Create", command);
    }

    public JsonResult OnPostCreate(CreateSlide command)
    {
        var result = _slideApplication.Create(command);
        return new JsonResult(result);
    }

    public IActionResult OnGetEdit(long id)
    {
        var slide = _slideApplication.GetDetails(id);
        return Partial("Edit", slide);
    }

    public JsonResult OnPostEdit(EditSlide command)
    {
        var result = _slideApplication.Edit(command);
        return new JsonResult(result);
    }

    public IActionResult OnGetRemove(long id)
    {
        var result = _slideApplication.Remove(id);
        if (result.IsSuccedded)
            return RedirectToPage("./Index");

        Message = result.Message;
        return RedirectToPage("./Index");
    }

    public IActionResult OnGetRestore(long id)
    {
        var result = _slideApplication.Restore(id);
        if (result.IsSuccedded)
            return RedirectToPage("./Index");

        Message = result.Message;
        return RedirectToPage("./Index");
    }
}

EndPoint/Areas/Administration/Pages/Shop/Films/Create.cshtml
@model ShopManagement.Application.Contracts.Film.CreateFilm

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد ویدیو جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان عکس</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Name" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="Name">
                    <span asp-validation-for="Name" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Url" class="control-label">لینک ویدیو</label>
                    <input type="text" class="form-control" asp-for="Url">
                    <span asp-validation-for="Url" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Description" class="control-label">توضیحات</label>
                    <input type="text" class="form-control" asp-for="Description">
                    <span asp-validation-for="Description" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

EndPoint/Areas/Administration/Pages/Shop/Films/Edit.cshtml
@model ShopManagement.Application.Contracts.Film.EditFilm

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش ویدیو: @Model.Name</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان عکس</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Name" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="Name">
                    <span asp-validation-for="Name" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Url" class="control-label">لینک ویدیو</label>
                    <input type="text" class="form-control" asp-for="Url">
                    <span asp-validation-for="Url" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Description" class="control-label">توضیحات</label>
                    <input type="text" class="form-control" asp-for="Description">
                    <span asp-validation-for="Description" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id"/>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

EndPoint/Areas/Administration/Pages/Shop/Films/Index.cshtml
@page
@using EndPoint.Areas.Administration.Pages.Shop.Films
@model IndexModel
@{
}

@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت ویدیو ها";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد اسلاید جدید</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست اسلایدها</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>عکس</th>
                                <th>عنوان</th>
                                <th>وضعیت</th>
                                <th>عملیات</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var item in Model.Films)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>
                                        <img src="~/ProductPictures/@item.Picture" style="height: 70px; width: 70px;"/>
                                    </td>
                                    <td>@item.Name</td>
                                    <td class="text-center">
                                        @if (!item.IsRemoved)
                                        {
                                            <i class="fa fa-check fa-3x text-success"></i>
                                        }
                                        else
                                        {
                                            <i class="fa fa-remove fa-3x text-danger"></i>
                                        }
                                    </td>
                                    <td>
                                        <a class="btn btn-warning waves-effect waves-light m-b-5"
                                           href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id })">
                                            <i class="fa fa-edit"></i> ویرایش
                                        </a>
                                        @if (!item.IsRemoved)
                                        {
                                            <a asp-page="./Index" asp-page-handler="Remove" asp-route-id="@item.Id"
                                               class="btn btn-danger waves-effect waves-light m-b-5">
                                                حذف
                                            </a>
                                        }
                                        else
                                        {
                                            <a asp-page="./Index" asp-page-handler="Restore" asp-route-id="@item.Id"
                                               class="btn btn-success waves-effect waves-light m-b-5">
                                                فعال سازی
                                            </a>
                                        }
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#datatable').dataTable();
        });
    </script>
}